theme: jekyll-theme-minimal
title: CS по выходным
description: Официальная страница учебного клуба\n
Добавляйтесь в группу в Telegram:\n
[https://t.me/joinchat/BX_C9wxMGVCfS2X6ycFeuA](https://t.me/joinchat/BX_C9wxMGVCfS2X6ycFeuA)
show_downloads: false
